name: brik_klontong
description: "Klontong, the Mobile Project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  file_picker: ^8.1.2
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.4.1
  flutter_screenutil: ^5.9.3
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  mocktail: ^1.0.4
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7

flutter:
  uses-material-design: true
